/*++++++++++++++++++++++++++++++++++++++++++++++++++++++*/
/*                                                      */
/* File:  Control_velocidad_difuso.c                    */
/*                                                      */
/* Author: Automatically generated by Xfuzzy            */
/*                                                      */
/*++++++++++++++++++++++++++++++++++++++++++++++++++++++*/

#include <stdio.h>
#include <math.h>
#include "Control_velocidad_difuso.h"

/*======================================================*/
/*  MembershipFunction MF_xfsg_triangle                 */
/*======================================================*/

/*------------------------------------------------------*/
/* Function to compute an equal relationship            */
/*------------------------------------------------------*/

static double MF_xfsg_triangle_equal(double x, double min, double max, double step, double a, double b, double c) {
    return (a<x && x<=b? (x-a)/(b-a) : (b<x && x<c? (c-x)/(c-b) : 0)); 

}

/*======================================================*/
/*  Operatorset OP_operador                             */
/*======================================================*/

/*------------------------------------------------------*/
/* Description of the operator AND                      */
/*------------------------------------------------------*/

static double OP_operador_And(double a, double b) {
    return (a<b? a : b); 

}

/*------------------------------------------------------*/
/* Description of the operator OR                       */
/*------------------------------------------------------*/

static double OP_operador_Or(double a, double b) {
    return (a>b? a : b); 

}

/*------------------------------------------------------*/
/* Description of the defuzzification method            */
/*------------------------------------------------------*/

static double OP_operador_Defuz(FuzzyNumber mf) {
 double min = mf.min;
 double max = mf.max;
     double num=0, denom=0;
     int i;
     for(i=0; i<mf.length; i++) {
      num += mf.degree[i] * mf.conc[i].center();
      denom += mf.degree[i];
     }
     if(denom==0) return (min+max)/2;
     return num/denom;

}


/*======================================================*/
/*  TypeLV TP_error                                     */
/*======================================================*/

/*------------------------------------------------------*/
/* Description of the label eNG                         */
/*------------------------------------------------------*/

static double TP_error_eNG_equal(double x){
   return MF_xfsg_triangle_equal(x,-120.0,120.0,0.9411764705882353,-120.0,-90.0,-60.0);
}

/*------------------------------------------------------*/
/* Description of the label eNM                         */
/*------------------------------------------------------*/

static double TP_error_eNM_equal(double x){
   return MF_xfsg_triangle_equal(x,-120.0,120.0,0.9411764705882353,-90.0,-60.0,-30.0);
}

/*------------------------------------------------------*/
/* Description of the label eNP                         */
/*------------------------------------------------------*/

static double TP_error_eNP_equal(double x){
   return MF_xfsg_triangle_equal(x,-120.0,120.0,0.9411764705882353,-60.0,-30.0,0.0);
}

/*------------------------------------------------------*/
/* Description of the label eZ                          */
/*------------------------------------------------------*/

static double TP_error_eZ_equal(double x){
   return MF_xfsg_triangle_equal(x,-120.0,120.0,0.9411764705882353,-30.0,0.0,30.0);
}

/*------------------------------------------------------*/
/* Description of the label ePP                         */
/*------------------------------------------------------*/

static double TP_error_ePP_equal(double x){
   return MF_xfsg_triangle_equal(x,-120.0,120.0,0.9411764705882353,0.0,30.0,60.0);
}

/*------------------------------------------------------*/
/* Description of the label ePM                         */
/*------------------------------------------------------*/

static double TP_error_ePM_equal(double x){
   return MF_xfsg_triangle_equal(x,-120.0,120.0,0.9411764705882353,30.0,60.0,90.0);
}

/*------------------------------------------------------*/
/* Description of the label ePG                         */
/*------------------------------------------------------*/

static double TP_error_ePG_equal(double x){
   return MF_xfsg_triangle_equal(x,-120.0,120.0,0.9411764705882353,60.0,90.0,120.0);
}

/*======================================================*/
/*  TypeLV TP_CambioError                               */
/*======================================================*/

/*------------------------------------------------------*/
/* Description of the label ceNG                        */
/*------------------------------------------------------*/

static double TP_CambioError_ceNG_equal(double x){
   return MF_xfsg_triangle_equal(x,-8.0,8.0,0.06274509803921569,-8.0,-6.0,-4.0);
}

/*------------------------------------------------------*/
/* Description of the label ceNM                        */
/*------------------------------------------------------*/

static double TP_CambioError_ceNM_equal(double x){
   return MF_xfsg_triangle_equal(x,-8.0,8.0,0.06274509803921569,-6.0,-4.0,-2.0);
}

/*------------------------------------------------------*/
/* Description of the label ceNP                        */
/*------------------------------------------------------*/

static double TP_CambioError_ceNP_equal(double x){
   return MF_xfsg_triangle_equal(x,-8.0,8.0,0.06274509803921569,-4.0,-2.0,0.0);
}

/*------------------------------------------------------*/
/* Description of the label ceZ                         */
/*------------------------------------------------------*/

static double TP_CambioError_ceZ_equal(double x){
   return MF_xfsg_triangle_equal(x,-8.0,8.0,0.06274509803921569,-2.0,0.0,2.0);
}

/*------------------------------------------------------*/
/* Description of the label cePP                        */
/*------------------------------------------------------*/

static double TP_CambioError_cePP_equal(double x){
   return MF_xfsg_triangle_equal(x,-8.0,8.0,0.06274509803921569,0.0,2.0,4.0);
}

/*------------------------------------------------------*/
/* Description of the label cePM                        */
/*------------------------------------------------------*/

static double TP_CambioError_cePM_equal(double x){
   return MF_xfsg_triangle_equal(x,-8.0,8.0,0.06274509803921569,2.0,4.0,6.0);
}

/*------------------------------------------------------*/
/* Description of the label cePG                        */
/*------------------------------------------------------*/

static double TP_CambioError_cePG_equal(double x){
   return MF_xfsg_triangle_equal(x,-8.0,8.0,0.06274509803921569,4.0,6.0,8.0);
}

/*======================================================*/
/*  TypeLV TP_salida                                    */
/*======================================================*/

/*------------------------------------------------------*/
/* Description of the label sNG                         */
/*------------------------------------------------------*/

static double TP_salida_sNG_equal(double x){
   return MF_xfsg_triangle_equal(x,-1.0,1.0,0.00784313725490196,-1.0,-0.75,-0.5);
}

static double TP_salida_sNG_center(){
   return -0.75;
}

/*------------------------------------------------------*/
/* Description of the label sNM                         */
/*------------------------------------------------------*/

static double TP_salida_sNM_equal(double x){
   return MF_xfsg_triangle_equal(x,-1.0,1.0,0.00784313725490196,-0.75,-0.5,-0.25);
}

static double TP_salida_sNM_center(){
   return -0.5;
}

/*------------------------------------------------------*/
/* Description of the label sNP                         */
/*------------------------------------------------------*/

static double TP_salida_sNP_equal(double x){
   return MF_xfsg_triangle_equal(x,-1.0,1.0,0.00784313725490196,-0.5,-0.25,0.0);
}

static double TP_salida_sNP_center(){
   return -0.25;
}

/*------------------------------------------------------*/
/* Description of the label sZ                          */
/*------------------------------------------------------*/

static double TP_salida_sZ_equal(double x){
   return MF_xfsg_triangle_equal(x,-1.0,1.0,0.00784313725490196,-0.25,0.0,0.25);
}

static double TP_salida_sZ_center(){
   return 0.0;
}

/*------------------------------------------------------*/
/* Description of the label sPP                         */
/*------------------------------------------------------*/

static double TP_salida_sPP_equal(double x){
   return MF_xfsg_triangle_equal(x,-1.0,1.0,0.00784313725490196,0.0,0.25,0.5);
}

static double TP_salida_sPP_center(){
   return 0.25;
}

/*------------------------------------------------------*/
/* Description of the label sPM                         */
/*------------------------------------------------------*/

static double TP_salida_sPM_equal(double x){
   return MF_xfsg_triangle_equal(x,-1.0,1.0,0.00784313725490196,0.25,0.5,0.75);
}

static double TP_salida_sPM_center(){
   return 0.5;
}

/*------------------------------------------------------*/
/* Description of the label sPG                         */
/*------------------------------------------------------*/

static double TP_salida_sPG_equal(double x){
   return MF_xfsg_triangle_equal(x,-1.0,1.0,0.00784313725490196,0.5,0.75,1.0);
}

static double TP_salida_sPG_center(){
   return 0.75;
}

/*======================================================*/
/*  Rulebase RL_reglas_controlador                      */
/*======================================================*/

static void RL_reglas_controlador(double error, double CambioError, double *Salida) {
 double _rl;

 double _Salida_degree[7];
 Consequent _Salida_conc[7];
 FuzzyNumber _Salida;
 _Salida.min = -1.0;
 _Salida.max = 1.0;
 _Salida.step = 0.00784313725490196;
 _Salida.length = 7;
 _Salida.degree = _Salida_degree;
 _Salida.conc = _Salida_conc;
 int _Salida_i = 0;

 double _error_eq[7];
 _error_eq[0] = TP_error_eNG_equal(error);
 _error_eq[1] = TP_error_eNM_equal(error);
 _error_eq[2] = TP_error_eNP_equal(error);
 _error_eq[3] = TP_error_eZ_equal(error);
 _error_eq[4] = TP_error_ePP_equal(error);
 _error_eq[5] = TP_error_ePM_equal(error);
 _error_eq[6] = TP_error_ePG_equal(error);

 double _CambioError_eq[7];
 _CambioError_eq[0] = TP_CambioError_ceNG_equal(CambioError);
 _CambioError_eq[1] = TP_CambioError_ceNM_equal(CambioError);
 _CambioError_eq[2] = TP_CambioError_ceNP_equal(CambioError);
 _CambioError_eq[3] = TP_CambioError_ceZ_equal(CambioError);
 _CambioError_eq[4] = TP_CambioError_cePP_equal(CambioError);
 _CambioError_eq[5] = TP_CambioError_cePM_equal(CambioError);
 _CambioError_eq[6] = TP_CambioError_cePG_equal(CambioError);

 _rl = OP_operador_Or(OP_operador_Or(OP_operador_Or(OP_operador_Or(OP_operador_Or(OP_operador_Or(OP_operador_Or(OP_operador_Or(OP_operador_Or(OP_operador_And(_error_eq[0],_CambioError_eq[1]),OP_operador_And(_error_eq[0],_CambioError_eq[0])),OP_operador_And(_error_eq[0],_CambioError_eq[2])),OP_operador_And(_error_eq[0],_CambioError_eq[3])),OP_operador_And(_error_eq[1],_CambioError_eq[0])),OP_operador_And(_error_eq[1],_CambioError_eq[1])),OP_operador_And(_error_eq[1],_CambioError_eq[2])),OP_operador_And(_error_eq[2],_CambioError_eq[0])),OP_operador_And(_error_eq[3],_CambioError_eq[0])),OP_operador_And(_error_eq[2],_CambioError_eq[1]));
 _Salida_degree[_Salida_i] = _rl;
 _Salida_conc[_Salida_i].equal = TP_salida_sNG_equal;
 _Salida_conc[_Salida_i].center = TP_salida_sNG_center;
 _Salida_i++;

 _rl = OP_operador_Or(OP_operador_Or(OP_operador_Or(OP_operador_Or(OP_operador_And(_error_eq[1],_CambioError_eq[3]),OP_operador_And(_error_eq[0],_CambioError_eq[4])),OP_operador_And(_error_eq[2],_CambioError_eq[2])),OP_operador_And(_error_eq[4],_CambioError_eq[0])),OP_operador_And(_error_eq[3],_CambioError_eq[1]));
 _Salida_degree[_Salida_i] = _rl;
 _Salida_conc[_Salida_i].equal = TP_salida_sNM_equal;
 _Salida_conc[_Salida_i].center = TP_salida_sNM_center;
 _Salida_i++;

 _rl = OP_operador_Or(OP_operador_Or(OP_operador_Or(OP_operador_Or(OP_operador_Or(OP_operador_And(_error_eq[1],_CambioError_eq[4]),OP_operador_And(_error_eq[0],_CambioError_eq[5])),OP_operador_And(_error_eq[2],_CambioError_eq[3])),OP_operador_And(_error_eq[3],_CambioError_eq[2])),OP_operador_And(_error_eq[5],_CambioError_eq[0])),OP_operador_And(_error_eq[4],_CambioError_eq[1]));
 _Salida_degree[_Salida_i] = _rl;
 _Salida_conc[_Salida_i].equal = TP_salida_sNP_equal;
 _Salida_conc[_Salida_i].center = TP_salida_sNP_center;
 _Salida_i++;

 _rl = OP_operador_Or(OP_operador_Or(OP_operador_Or(OP_operador_Or(OP_operador_Or(OP_operador_Or(OP_operador_And(_error_eq[1],_CambioError_eq[5]),OP_operador_And(_error_eq[0],_CambioError_eq[6])),OP_operador_And(_error_eq[2],_CambioError_eq[4])),OP_operador_And(_error_eq[3],_CambioError_eq[3])),OP_operador_And(_error_eq[4],_CambioError_eq[2])),OP_operador_And(_error_eq[6],_CambioError_eq[0])),OP_operador_And(_error_eq[5],_CambioError_eq[1]));
 _Salida_degree[_Salida_i] = _rl;
 _Salida_conc[_Salida_i].equal = TP_salida_sZ_equal;
 _Salida_conc[_Salida_i].center = TP_salida_sZ_center;
 _Salida_i++;

 _rl = OP_operador_Or(OP_operador_Or(OP_operador_Or(OP_operador_Or(OP_operador_Or(OP_operador_And(_error_eq[2],_CambioError_eq[5]),OP_operador_And(_error_eq[1],_CambioError_eq[6])),OP_operador_And(_error_eq[3],_CambioError_eq[4])),OP_operador_And(_error_eq[4],_CambioError_eq[3])),OP_operador_And(_error_eq[6],_CambioError_eq[1])),OP_operador_And(_error_eq[5],_CambioError_eq[2]));
 _Salida_degree[_Salida_i] = _rl;
 _Salida_conc[_Salida_i].equal = TP_salida_sPP_equal;
 _Salida_conc[_Salida_i].center = TP_salida_sPP_center;
 _Salida_i++;

 _rl = OP_operador_Or(OP_operador_Or(OP_operador_Or(OP_operador_Or(OP_operador_And(_error_eq[3],_CambioError_eq[5]),OP_operador_And(_error_eq[2],_CambioError_eq[6])),OP_operador_And(_error_eq[4],_CambioError_eq[4])),OP_operador_And(_error_eq[6],_CambioError_eq[2])),OP_operador_And(_error_eq[5],_CambioError_eq[3]));
 _Salida_degree[_Salida_i] = _rl;
 _Salida_conc[_Salida_i].equal = TP_salida_sPM_equal;
 _Salida_conc[_Salida_i].center = TP_salida_sPM_center;
 _Salida_i++;

 _rl = OP_operador_Or(OP_operador_Or(OP_operador_Or(OP_operador_Or(OP_operador_Or(OP_operador_Or(OP_operador_Or(OP_operador_Or(OP_operador_Or(OP_operador_And(_error_eq[4],_CambioError_eq[5]),OP_operador_And(_error_eq[3],_CambioError_eq[6])),OP_operador_And(_error_eq[4],_CambioError_eq[6])),OP_operador_And(_error_eq[5],_CambioError_eq[4])),OP_operador_And(_error_eq[5],_CambioError_eq[5])),OP_operador_And(_error_eq[5],_CambioError_eq[6])),OP_operador_And(_error_eq[6],_CambioError_eq[3])),OP_operador_And(_error_eq[6],_CambioError_eq[4])),OP_operador_And(_error_eq[6],_CambioError_eq[6])),OP_operador_And(_error_eq[6],_CambioError_eq[5]));
 _Salida_degree[_Salida_i] = _rl;
 _Salida_conc[_Salida_i].equal = TP_salida_sPG_equal;
 _Salida_conc[_Salida_i].center = TP_salida_sPG_center;
 _Salida_i++;

 *Salida = OP_operador_Defuz(_Salida);
}


/*======================================================*/
/*                   Inference Engine                   */
/*======================================================*/

void Control_velocidad_difusoInferenceEngine(double error, double CambioError, double *_d_Salida) {
 double Salida;
 RL_reglas_controlador(error, CambioError, &Salida);
 *_d_Salida = Salida;
}

